name: ðŸ“Š Sync Issues to GitHub Project

# Automatically add Issues and PRs to GitHub Project V2
# Addresses Issue #5 - Phase A: Data Persistence Layer

on:
  issues:
    types: [opened, labeled, assigned, reopened]
  pull_request:
    types: [opened, ready_for_review, reopened]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Add to Agentic OS Project

    steps:
      - name: Add Issue/PR to Project
        uses: actions/add-to-project@v0.5.0
        with:
          # TODO: Replace with actual project URL after creation
          project-url: https://github.com/users/ShunsukeHayashi/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: |
            enhancement
            bug
            documentation
            phase-7
            phase-8

      - name: Log Success
        run: |
          echo "âœ… Added ${{ github.event_name }} to Project"
          echo "   Type: ${{ github.event_name }}"
          echo "   Number: ${{ github.event.issue.number || github.event.pull_request.number }}"
          echo "   Title: ${{ github.event.issue.title || github.event.pull_request.title }}"

  set-initial-fields:
    runs-on: ubuntu-latest
    needs: add-to-project
    name: Set Project Custom Fields
    if: github.event_name == 'issues' && github.event.action == 'opened'

    steps:
      - name: Determine Priority from Labels
        id: priority
        run: |
          LABELS="${{ toJson(github.event.issue.labels.*.name) }}"

          if echo "$LABELS" | grep -q "ðŸ”¥.*Critical"; then
            echo "priority=P0-Critical" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -q "âš ï¸.*High"; then
            echo "priority=P1-High" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -q "phase-7"; then
            echo "priority=P1-High" >> $GITHUB_OUTPUT
          else
            echo "priority=P2-Medium" >> $GITHUB_OUTPUT
          fi

      - name: Determine Phase
        id: phase
        run: |
          LABELS="${{ toJson(github.event.issue.labels.*.name) }}"

          if echo "$LABELS" | grep -q "phase-7"; then
            echo "phase=Phase 7" >> $GITHUB_OUTPUT
          elif echo "$LABELS" | grep -q "phase-8"; then
            echo "phase=Phase 8" >> $GITHUB_OUTPUT
          else
            echo "phase=Backlog" >> $GITHUB_OUTPUT
          fi

      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const priority = '${{ steps.priority.outputs.priority }}';
            const phase = '${{ steps.phase.outputs.phase }}';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: `ðŸ¤– **AgenticOS Auto-Triage**

              This Issue has been automatically added to the Agentic OS Project.

              - **Priority**: ${priority}
              - **Phase**: ${phase}
              - **Status**: Pending

              A Coordinator Agent will review and assign appropriate specialists soon.

              ---
              *Automated by [project-sync.yml](.github/workflows/project-sync.yml)*`
            });

      # TODO: Once Project V2 custom fields API is stable, set fields via GraphQL
      # Currently, GitHub Actions doesn't have built-in support for Project V2 custom fields
      # Will need to use GraphQL API directly once project is created
