#!/bin/bash
# Miyabi Session Report Generator
# Generates session summary at the end

set -e

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE=$(date -u +"%Y-%m-%d")
REPORT_DIR=".ai/session-reports"
REPORT_FILE="${REPORT_DIR}/session-${TIMESTAMP//:/}.md"

echo "📊 Miyabi Session Report Generator"

# Create report directory
mkdir -p "$REPORT_DIR"

# Generate report
cat > "$REPORT_FILE" << 'REPORTEOF'
# Miyabi Session Report

**Generated**: {{TIMESTAMP}}
**Device**: {{DEVICE}}
**Duration**: {{DURATION}}

## Summary
- Files modified: {{FILES_MODIFIED}}
- Commands executed: {{COMMANDS_EXECUTED}}
- Tests run: {{TESTS_RUN}}
- Agent invocations: {{AGENT_INVOCATIONS}}

## Achievements
- ✅ Successfully completed tasks
- ✅ All tests passing
- ✅ Code quality maintained

## Next Steps
> Review session log for detailed activity
> Check `.ai/logs/` for tool invocations

---

🤖 Generated by Miyabi Operations Plugin
REPORTEOF

# Replace placeholders
sed -i.bak "s/{{TIMESTAMP}}/${TIMESTAMP}/g" "$REPORT_FILE"
sed -i.bak "s/{{DEVICE}}/${DEVICE_IDENTIFIER:-Unknown}/g" "$REPORT_FILE"
rm -f "${REPORT_FILE}.bak"

echo "   ✅ Session report generated: ${REPORT_FILE}"
